### PR TITLE
Adds tips

### PR DESCRIPTION
**Pull request by JohnOxford**
Will add more in later PR's, just removing the shitty ones and starting a list on fallout relevant ones.

### CODE REVIEW

**Comment by Sansaur** [comment]
you can add more by commiting more to this PR, I'd say you dedicate one day asking to players and admins for more tips and tricks they know (not only about FO13 but also about the server and general ss13 gameplay)

And well, just that, add more than those

**Comment by Official-Outcast13** [comment]
MOAR TEPS

**Comment by Sansaur** [comment]
Have you checked with the community to see if they know tips and tricks that are not in this document? And try to add some about roleplaying too. The "rank system" is great, although I'm sure it needs more factions to be added in.

And yeah, just that, add some roleplaying tips, like "You know you can play the game without shooting every player that moves? It can be an interesting experience to try and add dramatic effect to a situation" or "This is not Pixel Fallout Battle Royale"

**Comment by Harcourt1** [comment]
This is fine.

**Pull request merged**
