### PR TITLE
content additions and such

### PR DESCRIPTION
**Pull request by JohnOxford**
adds prime helmets
adds legion armors for each rank
adds scorched sierra power armor
changes the ncr general to a ncr captain
gives the captain scorched sierra
gives him a officer beret too
changes walkie talkie sprites
adds legion shields
adds light legion shields
lots of syntax changes
prefixes added to faction names
adds a master crafted machete gladius for admemes
changes the current axe sprite
probally some other shit i forgot to mention

### CODE REVIEW

**Review by John-Dang — DISMISSED** [review]
The changes appear to be nothing but positive. If the update functions properly, I give my approval!

**Review by Sansaur — DISMISSED** [review]
Sounds good, and it's good that this comes before a thing I'm gonna do about giving weapons "breaking power"

**Review by Sansaur — COMMENTED** [review]
Sounds good, and it's good that this comes before a thing I'm gonna do about giving weapons "breaking power".

But, actually, you should first check that this actually merges, Travis is saying otherwise. Compile locally and check it works first.

**Comment by JohnOxford** [comment]
it doesnt. trying to add a do not merge tag but thats generally given. i either fucked something up really bad or its not detecting entire files or some shit. i dunno ill have a look at it when i get back to my computer

**Comment by AndrewL97** [comment]
You have removed heaps of armor types, so job datums are upset that they can't find things
like the power armor, under armor.dm
I imagine that you have missed uploading wherever you moved that armor to?

**Comment by Sansaur** [comment]
I've read the logs and like 90% of the errors are undefined type paths used by other things, so yeah, it seems some of the things you've removed were being used by other items / datums / map objects... Whatever.

**Comment by JohnOxford** [comment]
i figured as much. ill be at a computer tonight and will unfuck it then.

**Comment by JohnOxford** [comment]
i lied im just going to try to fix this pr

**Comment by JohnOxford** [comment]
https://gyazo.com/ea8d890dbae11edece91c61ca6468730

it runs

**Review by Harcourt1 — COMMENTED** [review]
I mean, it works.

**Review by Sansaur — APPROVED** [review]
This shouldn't cause any troubles since it's mostly description changes and additions of items that basically already exist. I'm approving because it seems it might work, and the checks pass. But I'd like it if before you merged this you added screenshots of the changes in action inside the game.

**Pull request merged**
